service: lambda-python

frameworkVersion: ">=1.2.0 <2.0.0"

provider:
  name: aws
  runtime: python2.7

functions:
  tracker:
    handler: handler.tracker
    events:
      - http:
          path: ping
          method: get
  currentTime:
    handler: handler.endpoint
    events:
      - http:
          path: ping
          method: get
