service: lambda-python

frameworkVersion: ">=1.2.0 <2.0.0"

provider:
  name: aws
  runtime: python3.6

functions:
  tracker:
    handler: handler.tracker
    events:
      - schedule: rate(1 minute)
  timepls:
    handler: handler.timepls
    events:
      - http:
          path: ping
          method: get
